steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/expert-coaching-hub:$COMMIT_SHA', '.']
  
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/expert-coaching-hub:$COMMIT_SHA']
  
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
    - 'run'
    - 'deploy'
    - 'expert-coaching-hub'
    - '--image'
    - 'gcr.io/$PROJECT_ID/expert-coaching-hub:$COMMIT_SHA'
    - '--region'
    - 'us-central1'
    - '--platform'
    - 'managed'
    - '--allow-unauthenticated'
    - '--port'
    - '8080'
    - '--memory'
    - '1Gi'
    - '--cpu'
    - '1'
    - '--timeout'
    - '30s'
    - '--concurrency'
    - '80'
    - '--max-instances'
    - '100'
    - '--quiet'
    - '--set-cloud-run-key'

# Optional: Deploy to staging first
  # - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  #   entrypoint: gcloud
  #   args:
  #   - 'run'
  #   - 'deploy'
  #   - 'expert-coaching-hub-staging'
  #   - '--image'
  #   - 'gcr.io/$PROJECT_ID/expert-coaching-hub:$COMMIT_SHA'
  #   - '--region'
  #   - 'us-central1'
  #   - '--platform'
  #   - 'managed'
  #   - '--allow-unauthenticated'

substitutions:
  _REGION: us-central1

images:
  - 'gcr.io/$PROJECT_ID/expert-coaching-hub:$COMMIT_SHA'

# Configure build options
options:
  machineType: 'E2_HIGHCPU_8'
  diskSizeGb: 100
  logging: CLOUD_LOGGING_ONLY
