// Temporary types for course features
// These should be generated by Supabase once migrations are applied

export interface CourseReview {
  id: string;
  course_id: string;
  user_id: string;
  rating: number;
  review_text: string | null;
  created_at: string;
  profiles: {
    full_name: string;
    avatar_url: string | null;
  };
}

export interface CourseCertificate {
  id: string;
  course_id: string;
  user_id: string;
  certificate_url: string | null;
  certificate_id: string;
  issued_at: string;
  verification_status: string;
  expires_at: string | null;
  courses: {
    title: string;
  };
  profiles: {
    full_name: string;
  };
}

export interface CourseFile {
  id: string;
  course_id: string;
  lesson_id: string | null;
  module_id: string | null;
  file_name: string;
  file_path: string;
  file_type: string;
  file_size: number;
  mime_type: string;
  uploaded_by: string;
  uploaded_at: string;
  is_public: boolean;
  download_count: number;
  tags: string[];
  description: string | null;
}
