-- Practice Exercise Generator schema

-- Table: practice_exercise_sets
CREATE TABLE IF NOT EXISTS public.practice_exercise_sets (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  lesson_id UUID REFERENCES public.lessons(id) ON DELETE CASCADE,
  content_id UUID REFERENCES public.lesson_content(id) ON DELETE SET NULL,
  generated_by UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  difficulty TEXT CHECK (difficulty IN ('intro', 'intermediate', 'advanced')),
  skill_focus TEXT,
  target_audience TEXT,
  model_used TEXT,
  prompt_context JSONB,
  raw_output JSONB,
  status TEXT NOT NULL DEFAULT 'draft' CHECK (status IN ('draft','approved','rejected')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  approved_at TIMESTAMPTZ,
  CONSTRAINT practice_exercise_sets_lesson_or_content_chk
    CHECK (lesson_id IS NOT NULL OR content_id IS NOT NULL)
);

COMMENT ON TABLE public.practice_exercise_sets IS 'Stores AI-generated practice exercise sets for lessons and content.';

-- Indexes
CREATE INDEX IF NOT EXISTS idx_practice_exercise_sets_lesson
  ON public.practice_exercise_sets(lesson_id);

CREATE INDEX IF NOT EXISTS idx_practice_exercise_sets_generated_by
  ON public.practice_exercise_sets(generated_by);

-- updated_at trigger
DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_trigger WHERE tgname = 'practice_exercise_sets_updated_at'
  ) THEN
    CREATE TRIGGER practice_exercise_sets_updated_at
    BEFORE UPDATE ON public.practice_exercise_sets
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();
  END IF;
END $$;

-- Table: practice_exercise_items
CREATE TABLE IF NOT EXISTS public.practice_exercise_items (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  set_id UUID NOT NULL REFERENCES public.practice_exercise_sets(id) ON DELETE CASCADE,
  exercise_type TEXT NOT NULL CHECK (exercise_type IN ('multiple_choice','short_answer','fill_in_blank','scenario','flashcard')),
  question TEXT NOT NULL,
  answer TEXT,
  explanation TEXT,
  choices JSONB,
  difficulty TEXT,
  tags TEXT[],
  order_index INT NOT NULL DEFAULT 0,
  metadata JSONB,
  approved BOOLEAN NOT NULL DEFAULT false,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

COMMENT ON TABLE public.practice_exercise_items IS 'Individual practice exercises generated by AI and linked to a set.';

CREATE INDEX IF NOT EXISTS idx_practice_exercise_items_set
  ON public.practice_exercise_items(set_id);

CREATE INDEX IF NOT EXISTS idx_practice_exercise_items_type
  ON public.practice_exercise_items(exercise_type);

DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_trigger WHERE tgname = 'practice_exercise_items_updated_at'
  ) THEN
    CREATE TRIGGER practice_exercise_items_updated_at
    BEFORE UPDATE ON public.practice_exercise_items
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();
  END IF;
END $$;

-- Enable RLS
ALTER TABLE public.practice_exercise_sets ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.practice_exercise_items ENABLE ROW LEVEL SECURITY;

-- Helper expression for coach ownership
CREATE OR REPLACE VIEW public.v_practice_exercise_coach_scope AS
SELECT
  pes.id AS set_id,
  c.coach_id,
  pes.generated_by
FROM public.practice_exercise_sets pes
LEFT JOIN public.lessons l ON l.id = pes.lesson_id
LEFT JOIN public.course_modules cm ON cm.id = l.module_id
LEFT JOIN public.courses c ON c.id = cm.course_id;

-- Policies for coaches/admins managing their exercise sets
DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies WHERE schemaname = 'public' AND tablename = 'practice_exercise_sets' AND policyname = 'Coaches manage own practice sets'
  ) THEN
    CREATE POLICY "Coaches manage own practice sets"
      ON public.practice_exercise_sets
      FOR ALL
      USING (
        EXISTS (
          SELECT 1 FROM public.v_practice_exercise_coach_scope scope
          WHERE scope.set_id = practice_exercise_sets.id
            AND scope.coach_id = auth.uid()
        )
        OR generated_by = auth.uid()
      )
      WITH CHECK (
        EXISTS (
          SELECT 1 FROM public.v_practice_exercise_coach_scope scope
          WHERE scope.set_id = practice_exercise_sets.id
            AND scope.coach_id = auth.uid()
        )
        OR generated_by = auth.uid()
      );
  END IF;
END $$;

-- Students can view approved sets tied to their enrollments
DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies WHERE schemaname = 'public' AND tablename = 'practice_exercise_sets' AND policyname = 'Students view approved practice sets'
  ) THEN
    CREATE POLICY "Students view approved practice sets"
      ON public.practice_exercise_sets
      FOR SELECT
      USING (
        practice_exercise_sets.status = 'approved'
        AND EXISTS (
          SELECT 1
          FROM public.practice_exercise_sets pes
          JOIN public.lessons l ON l.id = pes.lesson_id
          JOIN public.course_modules cm ON cm.id = l.module_id
          JOIN public.courses c ON c.id = cm.course_id
          JOIN public.course_enrollments ce ON ce.course_id = c.id
          WHERE pes.id = practice_exercise_sets.id
            AND ce.user_id = auth.uid()
        )
      );
  END IF;
END $$;

-- Policies for practice_exercise_items
DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies WHERE schemaname = 'public' AND tablename = 'practice_exercise_items' AND policyname = 'Coaches manage own practice items'
  ) THEN
    CREATE POLICY "Coaches manage own practice items"
      ON public.practice_exercise_items
      FOR ALL
      USING (
        EXISTS (
          SELECT 1
          FROM public.practice_exercise_sets pes
          JOIN public.v_practice_exercise_coach_scope scope ON scope.set_id = pes.id
          WHERE pes.id = practice_exercise_items.set_id
            AND (scope.coach_id = auth.uid() OR scope.generated_by = auth.uid())
        )
      )
      WITH CHECK (
        EXISTS (
          SELECT 1
          FROM public.practice_exercise_sets pes
          JOIN public.v_practice_exercise_coach_scope scope ON scope.set_id = pes.id
          WHERE pes.id = practice_exercise_items.set_id
            AND (scope.coach_id = auth.uid() OR scope.generated_by = auth.uid())
        )
      );
  END IF;
END $$;

DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies WHERE schemaname = 'public' AND tablename = 'practice_exercise_items' AND policyname = 'Students view approved practice items'
  ) THEN
    CREATE POLICY "Students view approved practice items"
      ON public.practice_exercise_items
      FOR SELECT
      USING (
        practice_exercise_items.approved = true
        AND EXISTS (
          SELECT 1
          FROM public.practice_exercise_sets pes
          JOIN public.lessons l ON l.id = pes.lesson_id
          JOIN public.course_modules cm ON cm.id = l.module_id
          JOIN public.courses c ON c.id = cm.course_id
          JOIN public.course_enrollments ce ON ce.course_id = c.id
          WHERE pes.id = practice_exercise_items.set_id
            AND pes.status = 'approved'
            AND ce.user_id = auth.uid()
        )
      );
  END IF;
END $$;

-- Clean up view when dropping (optional, idempotent)
COMMENT ON VIEW public.v_practice_exercise_coach_scope IS 'Helper view to scope practice exercise sets to owning coach for RLS policies.';
