-- Create course certificates table
CREATE TABLE IF NOT EXISTS course_certificates (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  course_id UUID NOT NULL REFERENCES courses(id) ON DELETE CASCADE,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  certificate_url TEXT,
  certificate_id TEXT UNIQUE NOT NULL,
  issued_at TIMESTAMPTZ DEFAULT now(),
  template_version TEXT DEFAULT '1.0',
  verification_status TEXT DEFAULT 'valid' CHECK (verification_status IN ('valid', 'revoked', 'expired')),
  expires_at TIMESTAMPTZ, -- Optional expiry date
  UNIQUE(course_id, user_id)
);

-- Add indexes
CREATE INDEX idx_course_certificates_course_id ON course_certificates(course_id);
CREATE INDEX idx_course_certificates_user_id ON course_certificates(user_id);
CREATE INDEX idx_course_certificates_certificate_id ON course_certificates(certificate_id);

-- RLS Policies
ALTER TABLE course_certificates ENABLE ROW LEVEL SECURITY;

-- Users can view their own certificates
CREATE POLICY "Users can view own certificates" ON course_certificates FOR SELECT USING (
  user_id = auth.uid()
);

-- Public can verify certificates by certificate_id
CREATE POLICY "Public can verify certificates" ON course_certificates FOR SELECT USING (
  certificate_id IS NOT NULL
);

-- System can create certificates (triggered by course completion)
CREATE POLICY "System can create certificates" ON course_certificates FOR INSERT WITH CHECK (
  true -- This will be controlled by the trigger function
);

-- Grant permissions
GRANT ALL ON course_certificates TO authenticated;
GRANT SELECT ON course_certificates TO anon;

-- Function to generate certificate ID
CREATE OR REPLACE FUNCTION generate_certificate_id()
RETURNS TEXT AS $$
BEGIN
  RETURN 'CERT-' || upper(substring(encode(gen_random_bytes(16), 'hex'), 1, 12));
END;
$$ LANGUAGE plpgsql;

-- Function to issue certificate upon course completion
CREATE OR REPLACE FUNCTION issue_course_certificate(
  p_user_id UUID,
  p_course_id UUID
)
RETURNS UUID AS $$
DECLARE
  certificate_uuid UUID;
  certificate_id_text TEXT;
  coach_name TEXT;
  course_title TEXT;
  completion_date TEXT;
BEGIN
  -- Check if certificate already exists
  SELECT id INTO certificate_uuid
  FROM course_certificates
  WHERE user_id = p_user_id AND course_id = p_course_id;
  
  IF certificate_uuid IS NOT NULL THEN
    RETURN certificate_uuid; -- Certificate already exists
  END IF;
  
  -- Get course and coach information
  SELECT 
    c.title,
    p.full_name
  INTO course_title, coach_name
  FROM courses c
  JOIN profiles p ON c.coach_id = p.id
  WHERE c.id = p_course_id;
  
  -- Generate certificate
  certificate_id_text := generate_certificate_id();
  completion_date := to_char(now(), 'Month DD, YYYY');
  
  -- Insert certificate record
  INSERT INTO course_certificates (
    course_id,
    user_id,
    certificate_id,
    certificate_url -- Will be generated by the edge function
  ) VALUES (
    p_course_id,
    p_user_id,
    certificate_id_text,
    NULL -- URL will be set by certificate generation service
  ) RETURNING id INTO certificate_uuid;
  
  -- TODO: Trigger edge function to generate certificate PDF/image
  -- This would call a certificate generation service
  
  RETURN certificate_uuid;
END;
$$ LANGUAGE plpgsql;

-- Trigger to automatically issue certificate when course is completed
CREATE OR REPLACE FUNCTION trigger_issue_certificate()
RETURNS TRIGGER AS $$
BEGIN
  -- Only issue certificate if progress reaches 100% and status is completed
  IF NEW.progress_percentage >= 100 AND NEW.status = 'completed' THEN
    PERFORM issue_course_certificate(NEW.user_id, NEW.course_id);
  END IF;
  
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Create trigger on course_enrollments
CREATE TRIGGER course_completion_certificate_trigger
  AFTER UPDATE ON course_enrollments
  FOR EACH ROW EXECUTE FUNCTION trigger_issue_certificate();

-- View for certificate verification
CREATE OR REPLACE VIEW public.certificate_verification AS
SELECT 
  cc.certificate_id,
  cc.issued_at,
  cc.expires_at,
  cc.verification_status,
  c.title as course_title,
  p.full_name as student_name,
  coach_profile.full_name as coach_name,
  c.coach_id
FROM course_certificates cc
JOIN courses c ON cc.course_id = c.id
JOIN profiles p ON cc.user_id = p.id
JOIN profiles coach_profile ON c.coach_id = coach_profile.id
WHERE cc.verification_status = 'valid';

-- Function to verify certificate
CREATE OR REPLACE FUNCTION verify_certificate(p_certificate_id TEXT)
RETURNS TABLE (
  certificate_id TEXT,
  course_title TEXT,
  student_name TEXT,
  coach_name TEXT,
  issued_at TIMESTAMPTZ,
  expires_at TIMESTAMPTZ,
  verification_status TEXT,
  is_valid BOOLEAN
) AS $$
BEGIN
  RETURN QUERY
  SELECT 
    cv.certificate_id,
    cv.course_title,
    cv.student_name,
    cv.coach_name,
    cv.issued_at,
    cv.expires_at,
    cv.verification_status,
    (cv.verification_status = 'valid' AND 
     (cv.expires_at IS NULL OR cv.expires_at > now()))::BOOLEAN as is_valid
  FROM certificate_verification cv
  WHERE cv.certificate_id = p_certificate_id;
END;
$$ LANGUAGE plpgsql;
